### ISSUE TITLE
Step 2 of install example is using wrong syntax for route regular expression parameters

### ISSUE THREAD

**Issue by VFAndrew** [reindert-vetter/api-version-control#14]
It looks like currently the documentation is using slightly wrong syntax for [Regular Expression Parameter Constraints](https://laravel.com/docs/8.x/routing#parameters-regular-expression-constraints)

Current documentation is using syntax `->where(['version', '#[a-z]\d{1,3}#'])`

but i believe this should either be 
`->where('version', '#[a-z]\d{1,3}#')`
or
`->where(['version' => '#[a-z]\d{1,3}#'])`

**Comment by reindert-vetter** [comment]
You're right. This is also stated in my production code. Strange that it does work. Maybe it doesn't validate with regex, but then allow all letters.

Thanks! I'm going to adjust it tonight.

**Comment by reindert-vetter** [comment]
Shouldn't it be `->where(['version' => '[a-z]\d{1,3}'])` instead of `->where(['version' => '#[a-z]\d{1,3}#'])`? (without #)
and
Shouldn't it be `->where(['version' => '#v\d{1,3}#'])` instead of `->where(['version' => '#[a-z]\d{1,3}#'])`? (using the letter `v`)

Combined:
Shouldn't it be `->where(['version' => 'v\d{1,3}'])` instead of `->where(['version' => '#v\d{1,3}#'])`?

**Comment by reindert-vetter** [comment]
Readme modified
